### ISSUE TITLE
Project using aspectjx plugin

### ISSUE THREAD

**Issue by hiworld75018** [HujiangTechnology/AspectJX-Demo#3]
Hi, I am trying to use aspects on an android project but build failed with the exception
`
Execution failed for task ':app:transformClassesWithExtractJarsForInternalDebug'.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithExtractJarsForInternalDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
...
Caused by: java.lang.RuntimeException: error
	at com.android.build.gradle.internal.pipeline.IntermediateFolderUtils.parseScopeLevelFolders(IntermediateFolderUtils.java:444)
	at com.android.build.gradle.internal.pipeline.IntermediateFolderUtils.parseTypeLevelFolders(IntermediateFolderUtils.java:411)
	at com.android.build.gradle.internal.pipeline.IntermediateFolderUtils.computeNonIncrementalInputFromFolder(IntermediateFolderUtils.java:116)
	at com.android.build.gradle.internal.pipeline.IntermediateStream.asNonIncrementalInput(IntermediateStream.java:132)
	at com.android.build.gradle.internal.pipeline.TransformTask.computeNonIncTransformInput(TransformTask.java:246)
`

What I did to use aspectJX
- add android an library ("aspectjx") to the android studio project
- add to project gradle: resolutionStrategy { cacheChangingModulesFor 0, 'seconds' }
- add dependency to project gradle: 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.9'
- add dependency to library gradle: 'org.aspectj:aspectjrt:1.8.9'
- add to settings.gradle: include ':app', ':aspectjx'
- app to app gradle: compile project ':aspectjx'"

Did I miss something ?
Thanks for answering

**Comment by hiworld75018** [comment]
Please note that my app has 2 "flavors" (public and internal), hence the "transform...InternalDebug".

**Comment by hiworld75018** [comment]
In the app gradle, I also added

aspectjx {
    includeJarFilter 'MyProject/aspectjx'
    excludeJarFilter
}

The library source has one file: LibrarySDK.java (just like your demo)

**Comment by khataha92** [comment]
Make sure that instant run is inactive because it conflicts with aspectjx
